### ISSUE TITLE
Authentication Checklist

### ISSUE THREAD

**Issue by gonzalez-aj** [AngieMGonzalez/INDIVIDUAL-ASSIGNMENT-Team-Roster#3]
**As a User who is Logged OUT:**
- [x]  I should only be able to see the authentication screen
- [x]  I would like to be able to click on an authentication button/login-button and login via google

**As a User who is Logged IN:** 
- [x] I should not be able to see the authentication button/login-button
- [x] I should be able to see the Team view -- see all my data
- [x] should be able to see a log out button
