### ISSUE TITLE
Routing (MVP) checklist

### ISSUE THREAD

**Issue by gonzalez-aj** [AngieMGonzalez/INDIVIDUAL-ASSIGNMENT-Team-Roster#4]
This app is for authenticated users only (must use google to log-in)

**As an authenticated user:**
For TEAM:
- [x] create a '/team' page for routing to be able to see all the team cards on the dom
- [x] create a TEAM clickable link in navbar
- [x]  if I click the TEAM link in the navbar, I should navigate to '/team' and see an h1 tag that says 'Team'.

For NEW
- [x] create a '/new' page that includes a form to be able to create a new member in a team
- [x] create a NEW clickable link in navbar
- [x]  if I click the NEW link in the navbar, I should navigate to '/new' and see an h1 tag that says 'Add a Member'.
