### ISSUE TITLE
CREATE checklist

### ISSUE THREAD

**Issue by gonzalez-aj** [AngieMGonzalez/INDIVIDUAL-ASSIGNMENT-Team-Roster#5]
**Only available to authenticated users who log-in w/ google:**

- [x]  I should be able to click the NEW link in the navbar that displays a form to add a new member.
  - [x] when clicking NEW it will take us to create a new member path to '/new' 
  - [x] this '/new' will call the component MemberForm() with the jsx of the form:
    - [x] this form will intake an object
    - [x] we will create a createMember() API call that will push our new data up to firebase

- [x] when I create a member, the member object should include my uid.
  - [x] the form here will have to useState:formInput
  - [x] we will have to useAuth: user because this is authenticated
  - [x] we will have to useRouter: redirects so that we can tell the code which page to render

- [x] when I fill out the form and submit a new member should be created in firebase and should now show in my Team view.
