### ISSUE TITLE
Read checklist

### ISSUE THREAD

**Issue by gonzalez-aj** [AngieMGonzalez/INDIVIDUAL-ASSIGNMENT-Team-Roster#6]
### **As an authenticated user:**
- [x] I should be able to see the Team view with all the members I have created
- [x] I should not be able to see members that were created by another user
- [x] use the hook useAuth:user to ensure this
