### ISSUE TITLE
Update Members Checklist

### ISSUE THREAD

**Issue by gonzalez-aj** [AngieMGonzalez/INDIVIDUAL-ASSIGNMENT-Team-Roster#7]
### **As an authenticated user:**
- [x]  I should be able to see an edit button on each member card.
- [x]  when I click the edit button I should see a form with the member information pre-populated in the form.
- [x] I should be able to edit the information in the form and hit the submit button.
- [x] when I submit the edit form firebase should be updated (PATCH request) and the Team view should update
